version: '1.0'

services: 
  node_backend:
    container_name: js-blog
    image: js-blog:1.0
    build:
      context: .
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
      - DB_USER=yoad
      - DB_PASSWORD=Aa22899822
      - DB_NAME=buban_blog
      - DB_HOST=node_db
      - DB_DIALECT=postgres
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - EMAIL_USER=bubanblog@gmail.com
      - EMAIL_PASS=sellhdccsgijuiow
      - ACCESS_TOKEN_SECRET=bayr1348jn!@lkj7uabd093u&u34ya83mnxp
      - ACCESS_TOKEN_EXPIRY=3600s
      - REFRESH_TOKEN_SECRET=bayr1348jn!@hk31fazsfghwqe<ss13mnxp
      - REFRESH_TOKEN_DURATION=28800s
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=yoad
      - POSTGRES_PASSWORD=Aa22899822
      - POSTGRES_DB=buban_blog
    volumes: 
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
    